# Generated by Django 3.1 on 2020-08-04 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Time started')),
                ('start_position', models.JSONField()),
                ('bounding_box', models.JSONField()),
                ('elapsed_time', models.DurationField(verbose_name='Elapsed Time')),
                ('timer_time', models.DurationField(verbose_name='Timed Time')),
                ('distance', models.FloatField(verbose_name='Distance Traveled')),
                ('strides', models.IntegerField()),
                ('speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('calories', models.FloatField()),
                ('ascent', models.FloatField()),
                ('descent', models.FloatField()),
                ('lap_count', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('max_heart_rate', models.IntegerField()),
                ('cadence', models.IntegerField()),
                ('max_cadence', models.IntegerField()),
                ('aerobic_training_effect', models.FloatField()),
                ('anaerobic_training_effect', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('start_position', models.JSONField()),
                ('end_position', models.JSONField()),
                ('bounding_box', models.JSONField()),
                ('elapsed_time', models.DurationField()),
                ('timer_time', models.DurationField()),
                ('distance', models.FloatField()),
                ('strides', models.IntegerField()),
                ('speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('calories', models.IntegerField()),
                ('ascent', models.FloatField()),
                ('descent', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('max_heart_rate', models.IntegerField()),
                ('cadence', models.IntegerField()),
                ('max_cadence', models.IntegerField()),
                ('lap_trigger', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('air_power', models.IntegerField()),
                ('form_power', models.IntegerField()),
                ('ground_contact', models.IntegerField()),
                ('record_start', models.IntegerField()),
                ('record_end', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
            ],
        ),
    ]
