# Generated by Django 3.1 on 2020-08-08 23:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_record'), ('app', '0003_auto_20200804_1833'), ('app', '0004_auto_20200805_1517'), ('app', '0005_auto_20200805_2225'), ('app', '0006_powercurveentry')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Time started')),
                ('elapsed_time', models.FloatField(verbose_name='Elapsed Time')),
                ('timer_time', models.FloatField(verbose_name='Timed Time')),
                ('distance', models.FloatField(verbose_name='Distance Traveled')),
                ('strides', models.IntegerField()),
                ('speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('calories', models.FloatField()),
                ('ascent', models.FloatField()),
                ('descent', models.FloatField()),
                ('lap_count', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('max_heart_rate', models.IntegerField()),
                ('cadence', models.IntegerField()),
                ('max_cadence', models.IntegerField()),
                ('aerobic_training_effect', models.FloatField()),
                ('anaerobic_training_effect', models.FloatField()),
                ('start_position_lat', models.FloatField(default=0)),
                ('start_position_long', models.FloatField(default=0)),
                ('max_power', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('elapsed_time', models.FloatField()),
                ('timer_time', models.FloatField()),
                ('distance', models.FloatField()),
                ('strides', models.IntegerField()),
                ('speed', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('calories', models.IntegerField()),
                ('ascent', models.FloatField()),
                ('descent', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('max_heart_rate', models.IntegerField()),
                ('cadence', models.IntegerField()),
                ('max_cadence', models.IntegerField()),
                ('lap_trigger', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('air_power', models.IntegerField()),
                ('form_power', models.IntegerField()),
                ('ground_contact', models.IntegerField()),
                ('record_start', models.IntegerField()),
                ('record_end', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
                ('end_position_lat', models.FloatField(default=0)),
                ('end_position_long', models.FloatField(default=0)),
                ('end_time', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0))),
                ('start_position_lat', models.FloatField(default=0)),
                ('start_position_long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('distance', models.FloatField()),
                ('speed', models.FloatField()),
                ('altitude', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('cadence', models.IntegerField()),
                ('power', models.IntegerField()),
                ('ground_time', models.IntegerField()),
                ('air_power', models.IntegerField()),
                ('form_power', models.IntegerField()),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
                ('lap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lap')),
                ('position_lat', models.FloatField(default=0)),
                ('position_long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PowerCurveEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.activity')),
            ],
        ),
    ]
