# Generated by Django 3.1 on 2020-08-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('position', models.JSONField()),
                ('distance', models.FloatField()),
                ('speed', models.FloatField()),
                ('altitude', models.FloatField()),
                ('heart_rate', models.IntegerField()),
                ('cadence', models.IntegerField()),
                ('power', models.IntegerField()),
                ('ground_time', models.IntegerField()),
                ('air_power', models.IntegerField()),
                ('form_power', models.IntegerField()),
            ],
        ),
    ]
