# Generated by Django 3.1 on 2020-08-04 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.activity'),
        ),
        migrations.AddField(
            model_name='record',
            name='lap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lap'),
        ),
    ]
