# Generated by Django 3.1 on 2020-08-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200805_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_power',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='power',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.FloatField(verbose_name='Elapsed Time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='timer_time',
            field=models.FloatField(verbose_name='Timed Time'),
        ),
        migrations.AlterField(
            model_name='lap',
            name='elapsed_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lap',
            name='timer_time',
            field=models.FloatField(),
        ),
    ]
